export const PROFILE = {
  owner: {
    handle: "az1nn",
    name: "Alan",
    headline: "Human engineering, amplified by AI.",
  },
  twin: {
    id: "ai-twin",
    name: "AI Twin",
    kind: "twin",
    short: "A digital extension of the same engineering loop: research, architecture, documentation, automation and building.",
    capabilities: ["Research", "Architecture", "Documentation", "Automation", "Code", "Iteration"],
    position: [1.92, 0.35, 1.05],
    states: {
      idle: {
        label: "IDLE",
        description: "Observing the system and waiting for a new problem to solve.",
        color: "#38bdf8",
        emissive: "#075985",
        intensity: 0.7,
      },
      thinking: {
        label: "THINKING",
        description: "Mapping context, constraints, dependencies and the next useful move.",
        color: "#22d3ee",
        emissive: "#0e7490",
        intensity: 1.25,
      },
      building: {
        label: "BUILDING",
        description: "Turning a plan into code, automation, documentation and shippable systems.",
        color: "#d946ef",
        emissive: "#86198f",
        intensity: 1.6,
      },
    },
  },
  activity: {
    endpoint: "https://api.github.com/users/az1nn/events/public?per_page=30",
    maxNodes: 18,
    label: "PUBLIC GITHUB ACTIVITY",
  },
  conversation: {
    mode: "local-grounded",
    maxHistory: 12,
    activityCacheTtlMs: 300000,
    gateway: {
      enabled: false,
      version: "0.5",
      endpoint: null,
      timeoutMs: 6000,
      clientProfileVersion: "0.4.0",
    },
    suggestions: [
      "What are you building now?",
      "How are CPXLABS Admin and MyHub related?",
      "Tell me about OpenBand",
      "Show recent activity",
    ],
  },
  timeline: [
    {
      phase: "01",
      title: "Build",
      summary: "Ship full-stack products and learn through working systems.",
    },
    {
      phase: "02",
      title: "Systemize",
      summary: "Turn repeated engineering decisions into reusable architecture, specifications and automation.",
    },
    {
      phase: "03",
      title: "Augment",
      summary: "Use LLMs, RAG and agents as leverage inside a deliberate engineering process.",
    },
    {
      phase: "04",
      title: "Graph",
      summary: "Connect projects, decisions and delivery evidence into a living engineering map.",
    },
  ],
  relations: [
    {
      source: "cpxlabs-admin",
      target: "myhub",
      label: "Spec + Graph Engineering",
      strength: 0.95,
    },
    {
      source: "cpxlabs-admin",
      target: "openband",
      label: "Product architecture",
      strength: 0.58,
    },
    {
      source: "pg-researcher",
      target: "zapizapi",
      label: "AI intake + knowledge",
      strength: 0.9,
    },
    {
      source: "cpx-labs",
      target: "openband",
      label: "Interactive web",
      strength: 0.72,
    },
    {
      source: "myhub",
      target: "zapizapi",
      label: "Personal systems",
      strength: 0.54,
    },
    {
      source: "pg-researcher",
      target: "myhub",
      label: "Structured knowledge",
      strength: 0.62,
    },
  ],
  projects: [
    {
      id: "openband",
      name: "OpenBand",
      kind: "project",
      category: "Creative systems",
      status: "Active",
      short: "Music creation, immersive product UX and creative tooling.",
      url: "https://github.com/az1nn/openband",
      tags: ["React", "Audio", "Product UX"],
      position: [-3.45, 1.7, -0.35],
      scale: 0.42,
    },
    {
      id: "cpxlabs-admin",
      name: "CPXLABS Admin",
      kind: "project",
      category: "Engineering platform",
      status: "Active",
      short: "Enterprise React/Vite architecture, Spec Kit and Engineering Graph workflows.",
      url: "https://github.com/az1nn/cpxlabs-admin",
      tags: ["Vite", "React", "Graph Engineering"],
      position: [3.3, 1.85, -0.7],
      scale: 0.48,
    },
    {
      id: "myhub",
      name: "MyHub",
      kind: "project",
      category: "Personal systems",
      status: "Active",
      short: "Spec-driven app foundations with graph-oriented engineering workflows.",
      url: "https://github.com/az1nn/myhub",
      tags: ["Spec-Driven", "Neo4j", "Architecture"],
      position: [4.0, -0.2, -0.9],
      scale: 0.4,
    },
    {
      id: "pg-researcher",
      name: "PG Researcher",
      kind: "project",
      category: "AI research",
      status: "Active",
      short: "Research workflows, structured knowledge and AI-assisted publishing.",
      url: "https://github.com/az1nn/pg-researcher",
      tags: ["LLM", "Research", "Knowledge"],
      position: [3.35, -2.0, 0.05],
      scale: 0.38,
    },
    {
      id: "zapizapi",
      name: "Zapizapi",
      kind: "project",
      category: "Automation",
      status: "Exploring",
      short: "Messaging abstraction and webhook-driven intake for AI-assisted triage.",
      url: "https://github.com/az1nn/zapizapi",
      tags: ["Messaging", "Webhooks", "Automation"],
      position: [-0.4, -3.35, -1.0],
      scale: 0.35,
    },
    {
      id: "cpx-labs",
      name: "CPX Labs",
      kind: "project",
      category: "Experiments",
      status: "Active",
      short: "Product engineering, automation and interactive web experiments.",
      url: "https://github.com/az1nn/cpx-labs",
      tags: ["Three.js", "Automation", "Web"],
      position: [-3.05, -1.9, 0.3],
      scale: 0.43,
    },
  ],
};
