// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Watchlist.Api.Data;

#nullable disable

namespace Watchlist.Api.Migrations;

[DbContext(typeof(WatchlistDbContext))]
[Migration("20260917130000_InitialWatchlist")]
partial class InitialWatchlist
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("Watchlist.Api.Domain.WatchlistItem", b =>
        {
            b.Property<Guid>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.Property<string>("ContentId")
                .HasMaxLength(120)
                .HasColumnType("character varying(120)")
                .HasColumnName("content_id");

            b.Property<DateTimeOffset>("AddedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("added_at");

            b.HasKey("UserId", "ContentId");

            b.ToTable("watchlist_items");
        });
#pragma warning restore 612, 618
    }
}
